# This is a basic workflow to help you get started with Actions

name: Test, publish coverage and lint with flake8

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.10"
          
      - name: Set up dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install poetry
          poetry install
          
      - name: Test with pytest
        run: poetry run pytest
        
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: poetry run pytest --cov=page_loader --cov-report xml
          
      - name: Lint with flake8
        run: poetry run flake8 page_loader
